### ISSUE TITLE
Script no longer disables farm mode after initiating a run

### ISSUE THREAD

**Issue by khalani** [swiftb/clicker-heroes-sw1ft-bot#10]
After updating to the latest version, the script does not automatically disable farm mode when initiating a run.

**Comment by swiftb** [comment]
What exactly are you referring to? You saying that a Speed Run does not toggle progression on?

The Vision Run guarantees it since it actively checks the progression icon every now and then.

**Comment by khalani** [comment]
Yeah. Speed run doesn't toggle progression on.

**Comment by khalani** [comment]
Nvm. I did a hard reset to the latest commit. Seems to be working now. I still have no idea what exactly was wrong.
