### ISSUE TITLE
Not leveling heroes properly

### ISSUE THREAD

**Issue by marcoskm** [swiftb/clicker-heroes-sw1ft-bot#11]
It always level some heroes twice (400) and in the end some heroes don't get leveled, how to fix it?

**Comment by swiftb** [comment]
I assume you are talking about the Speed Run init step. If you have set your `irisLevel` correctly, it is supposed to level all from Cid down to Frostleaf.

This is assuming a high enough Iris (>145), plus a clickable or a Midas start. If anyone between those two are still missed, try to search for "74" in the ch_sw1ft_bot.ahk file and change that to "73".

**Comment by marcoskm** [comment]
Yes and No.
What I mean is this:

http://images.akamai.steamusercontent.com/ugc/610603922564881209/DD8664FD7D73F74C630FE28C5589F0557C058328/
http://images.akamai.steamusercontent.com/ugc/610603922564881849/D74E2683DE08ECDEB8E2D4C20B42B455A913DBB3/
http://images.akamai.steamusercontent.com/ugc/610603922564882438/FD3C5922A1BF05C1387D09472CC797050C03D603/
http://images.akamai.steamusercontent.com/ugc/610603922564883000/BB74379930ABE422949F6637EDC974A0CBB34399/
http://images.akamai.steamusercontent.com/ugc/610603922564883484/846AE688C271A014ABC2788BC8496D9A42854471/
http://images.akamai.steamusercontent.com/ugc/610603922564884129/64642E5DC9860CEFE2FB99DE81EA99D99CAF5239/
http://images.akamai.steamusercontent.com/ugc/610603922564884561/13F9E21BBEE262A47DA15E2326C84012372C893A/
http://images.akamai.steamusercontent.com/ugc/610603922564885092/4E71D767B69D050CF488E0D28E8265CF3DB22462/

irisLevel := 1579

gildedRanger := 8

Optimal level: 2560 (according to http://philni.neocities.org/ancientssoul.html)

**Comment by swiftb** [comment]
The current way of doing it was initially called "plan b", a simple "brute force" way of getting the job done introduced in v3.0. Back then I also had a rather convoluted way of doing it "perfectly". If you are interested you can search for "initPlanB" [here](https://github.com/swiftb/clicker-heroes-sw1ft-bot/blob/467dd6583f3bf8d9834d158310aa607baae56acc/ch_sw1ft_bot.ahk).

Each "threshold" in Iris that would give you enough gold for a new ranger to spawn, required a different "scrolling pattern". Look [here](https://github.com/swiftb/clicker-heroes-sw1ft-bot/blob/467dd6583f3bf8d9834d158310aa607baae56acc/system/ch_bot_default_settings.ahk) and search for "initDownClicks".

When they released the 5 new rangers, I just gave up. It was just way to much work to keep it operational.

If you want it more "neat and tidy", I recommend using the Vision Run.

**Comment by marcoskm** [comment]
Okay, thanks!
