### ISSUE TITLE
Addition to the InitRun

### ISSUE THREAD

**Issue by vasilvalchev** [swiftb/clicker-heroes-sw1ft-bot#12]
Heya, you could add an EDR combo right after the initial run final checks to boost up the DPS a bit right here:

Near the end of the InitRun section:

```
        if (!locateImage(imgSkillLocked)) {
            hasNoSkillLocked := true
            activateSkills("8-6-9") ; <---- Here goes the combo!
        }
```

After verifying everything was bought out and the checks were made, you just EDR and go do the Vision run :)

**Comment by vasilvalchev** [comment]
To prevent major bugs or issues with the earlyGameMode mode the above can be changed easily as the following, or customized elsewhere. Just the point i chose seems to be perfect for running the combo. Here comes the modified source:

```
        if (!locateImage(imgSkillLocked)) {
            hasNoSkillLocked := true
            if (!earlyGameMode) {
                activateSkills("8-6-9")
            }
        }
```

**Comment by swiftb** [comment]
Why not use the existing `activateSkillsAtStart` option with whatever combo you fancy?

**Comment by vasilvalchev** [comment]
Yep, that would work too. Didn't check in details the function `activateSkillsAtStart` earlier, so the only thing left for the user is to customize the combo.

```
        initRun()
        if (activateSkillsAtStart) {
            clickerStart(clickerDuration)
            activateSkills(speedRunStartCombo[2])
        }
```

What i offered seems to be there actually, right after the InitRun()
`speedRunStartCombo := comboStart2` 
where 
`comboStart2 := [15*60, "8-5-2-3-4-7-6-9"] ; requires deepRunClicks set to true`
and we need the 2nd field of the array. Completely customizable...

Good point mate! Thanks!
