### ISSUE TITLE
new clickable

### ISSUE THREAD

**Issue by jjurkus** [swiftb/clicker-heroes-sw1ft-bot#13]
Since a day or so there is a new clickable, I've created this png, it seems to work for me.

![clickable_bag](https://cloud.githubusercontent.com/assets/9963052/12763033/89fe1898-c9f2-11e5-9d00-b64115128051.png)

**Comment by swiftb** [comment]
Did already push out that to the dev branch (very) early today.

**Comment by jjurkus** [comment]
Oh, bugger, I was of course not looking there.
