### ISSUE TITLE
InitRun() Addition

### ISSUE THREAD

**Issue by SilenceKillz777** [swiftb/clicker-heroes-sw1ft-bot#15]
I was wondering if you could add a timer on initRun() since that would level up all heroes and buy upgrades. Maybe something users can customize? I was thinking of auto initRun() maybe once every 120 seconds because in the speedrun, the bot doesn't scroll down whenever a new hero unlocks.

Note: Maybe a second initRun() function that doesn't click so it doesn't break idle. Something that can be used in both speed run and deep run.

**Comment by swiftb** [comment]
The initRun function is only supposed to level all heroes between Cid and FL once. Hence the rather high minimum (>145) Iris requirement for the (blind) Speed Run.

The Vision Run on the other hand can start earlier on a transitional hero/ranger and will not call initRun until it has reached zone 146.

**Comment by SilenceKillz777** [comment]
For the deep run, the bot doesnt automatically level up the highest hero unlocked when it does unlock though. Is there a way to get the bot to level up the hero as soon as it unlocks?

**Comment by swiftb** [comment]
Snippet from the readme:

> The Deep run is expecting to start where a Speed run finishes. Start it manually with Ctrl+F2, or set hybridMode to true to automatically start it.

It will stay on your gilded ranger for as long as you tell it too. If you are doing a longer deep run (days), you will have to re-gild and re-position the new ranger to let the bot continue on.
