### ISSUE TITLE
Accidentally respec of ancients in 4.0.0

### ISSUE THREAD

**Issue by jjurkus** [swiftb/clicker-heroes-sw1ft-bot#16]
Maybe I'm doing something wrong with the settings, but I've had the script removing all my ancients two times now. It seems to also hang on ascending, because the junk pile of the relics have not been salvaged.

I've double checked the various settings, but everything else works. It's not every run it does this. I have set the logfile to trace, and hope to find something.

**Comment by swiftb** [comment]
Removing ancients? You're saying the script is for some reason clicking on the ancients tab, then scrolling down to the bottom and clicking the respec button? The only time it should ever head into that tab, would be if you set it to level Solomon after each ascension.

As for salvaging relics, I know that the current code can't handle the case where you e.g. finish a relic merc quest, giving you more relics than can fit on one row. Unless you manually salvage these relics, the bot will miss the button as it just clicks on fixed coordinates.

**Comment by jjurkus** [comment]
I have levelSolomon set to false, so that shouldn't be it.

If you haven't heard of this at all, it might be a glitch or some weird thing. I thought it happened when levelling vaagur, kumawakamaru or chronos, without adjusting them in ch_bot_settings.ahk. Tried that, that's not it. I also tried with a relic that should be salvaged, to see if something was wrong with that.
Anyway, I'm rather cautious and try to save twice a day. I am not able to reproduce it. It might be a problem in clicker heroes itself, which got fixed without them changing the version number. I don't know.

So I think you can close this. I want to thank you for doing a good job, and for teaching me the basics of autohotkey. I've used the 'framework' of the monster clicker for something else (RCM, race clicking thingy, based on swarm simulator.) Before I couldn't never figure out how to exactly work with autohotkey. Now I have a template to use for the most basic things and learn from that. I've learned autocad lisp the same way, by looking at other code which was simple enough for me to modify. So thanks again! :-)

**Comment by swiftb** [comment]
Yup, getting the basics of AHK is pretty easy with the help from Google. GL with your little project! :)
