### ISSUE TITLE
New heroes

### ISSUE THREAD

**Issue by kittykiller** [swiftb/clicker-heroes-sw1ft-bot#18]
Any chance of adding the new heroes?

**Comment by swiftb** [comment]
Have not tested myself as I stopped playing CH, but the bot should work fine as long as you keep the new heroes gilded.

**Comment by kittykiller** [comment]
Not sure it's related but when I get the new heroes available at the bottom the bot seems to break.
It will not use skills and it just scrolls from top to bottom and clicks the gilded hero 4-5 times then scrolls back to the top and back down and just keeps doing that.

The odd thing is that if I ascend and start a fresh game it will work as intended even with the new heroes, but if I close the game and the bot and start from where I left off it does the scrolling thing and doesn't use the skills.

[2016-10-12.txt](https://github.com/swiftb/clicker-heroes-sw1ft-bot/files/525601/2016-10-12.txt)

I also notice in the log it says "hasAscendButton = false" but I do have the Ascend button.

I can send you my save game if that would help any.

**Comment by swiftb** [comment]
Sometimes temporary glitches like that can be fixed by re-sizing the browser window and click Alt+F6.
