### ISSUE TITLE
Script doesn't disable "farm mode"

### ISSUE THREAD

**Issue by add1ct3dd** [swiftb/clicker-heroes-sw1ft-bot#4]
Hey,

So I have the script working, but on ascending, it doesn't enabled progression mode automatically, so it just gets stuck constantly farming whatever level I'm on (Iris dependent), is there a way to do this? I looked through the options but didn't see anything.

**Comment by swiftb** [comment]
The script just sends "a" to the CH window in the same way as it sends 1-9 to trigger skills. Sounds very strange that this shouldn't work.

Try run the script as administrator and see if that makes any difference.

**Comment by swiftb** [comment]
Have found a possible fix for this issue. See [this thread](https://www.reddit.com/r/ClickerHeroes/comments/3a3bmy/autohotkey_hs_speed_farming_script/cwph259).

**Comment by swiftb** [comment]
The latest 3.0.1 version include a fix to better handle _non-qwerty_ keyboards.
