### ISSUE TITLE
Proposal for a working 'smart image recognition'

### ISSUE THREAD

**Issue by TransDOT** [swiftb/clicker-heroes-sw1ft-bot#6]
Hi,
I don't know how to contact you directly therefore I try it that way. I'm using your bot for a while now and I have modified it a little bit for my purposes and I wanted it to share with you. Actually I've modified the getClickable() function in order to collect the clickables during the run without breaking the idle mode. Please find attached the modified and added functions: 

;1. 
getClickableV2() {
    global
    if (getClickable = 1) { ; getClickable defined at ch_bot_settings.ahk

xarr := Array("527", "764", "1009", "874", "1053", "748") ; create an array with n items
yarr := Array("490", "385", "457", "514", "446", "436") ; create an array with n items

;because the clickable is semitransparent we need a smart solution which allows an approx. color of the clickable. in that case i choose the orange tommy. White (Snow) Background for the max. Values and dark red for the min. values
c1min := 0 ; minimum 'blue' saturation
c1max := 26 ; max. 'blue' saturation (0-255)
c2min := 201 ; min. 'green' saturation
c2max := 227 ; max. 'green' saturation
c3min := 229 ; min. 'red' saturation
c3max := 255 ; max. 'red' saturation

Loop, % xarr.MaxIndex() ; maxindex() = 6 currently (n items)
{
PixelGetColor, cBGR1 , xarr[A_Index],  yarr[A_Index] ; A_Index beginns allways with 1 and ends with 'break' or predefined loop-interations 
Stringmid, c1, cBGR1, 3, 2 ; get HexString for 'blue' value
StringMid, c2, cBGR1, 5, 2 ; get hexstring for 'green' value
StringRight, c3, cBGR1, 2 ; get hexsting for 'red' value

;Converts Hex values to Decimal values
c1:= ConvertBase(16, 10, c1) 
c2:= ConvertBase(16, 10, c2) 
c3:= ConvertBase(16, 10, c3) 
;clicks to a clear area in order to remove the pop-up information of the lvlup() function, which can cover the clickable when it is located in the appropiate area
ControlClick, x472 y292, ahk_id %chWinId%,,, 1, NA

;if 'orange' color is located in one of the 6 defined x/y-positions clickable will be picked up without breaking idle mode
if ((c1 >= c1min and c1 <= c1max) and (c2 >= c2min and c2 <= c2max) and (c3 >= c3min and c3 <= c3max) ){
xPos1:= xarr[A_Index]
yPos1:= yarr[A_Index]
;function clickpos() didn't work for me in all cases. dunno why. there I choose the original controlclick method
ControlClick, x%xPos1% y%yPos1%, ahk_id %chWinId%,,, 1, NA
}
}

;2. copied from a solution forum somewhere via google)
ConvertBase(InputBase, OutputBase, number)
{
    static u := A_IsUnicode ? "_wcstoui64" : "_strtoui64"
    static v := A_IsUnicode ? "_i64tow"    : "_i64toa"
    VarSetCapacity(s, 65, 0)
    value := DllCall("msvcrt.dll\" u, "Str", number, "UInt", 0, "UInt", InputBase, "CDECL Int64")
    DllCall("msvcrt.dll\" v, "Int64", value, "Str", s, "UInt", OutputBase, "CDECL")
    return s
}

; 3. 
lvlUp(seconds, buyUpgrades, button, stint, stints, phase) { ; added 'phase' in order to tag the current progession-level
    global

```
exitThread := false
local y := yLvl + oLvl * (button - 1)
local title := "Speed Run Progress (" . stint . "/" . stints . ")"

;startMouseMonitoring()
startProgress(title, 0, seconds // barUpdateDelay)

if (buyUpgrades) {
    ctrlClick(xLvl, y)
    buyAvailableUpgrades()
}
maxClick(xLvl, y)

local t := 0

loop % seconds
{
    if (exitThread) {
        stopProgress()
        stopMouseMonitoring()
        showSplashAlways("Speed run aborted!")
        exit
    }
    if (mod(t, lvlUpDelay) = 0) {
        ctrlClick(xLvl, y)
    }
    t += 1
    updateProgress(t // barUpdateDelay, seconds - t)
    sleep 1000
    if (phase < 4){ ; if NOT the last progression mode phase get clickable without monitoring the remaining time
    getClickableV2()
}
    if ((seconds - t) > 660){ ; if remaining time of idle speed run below above 11 minutes clickables will be automatically collected. I've tried 10 mintues (600 secs.) but by in some rare cases 1 of 60 (approx.) that time frame was not enough and ascending occured without clickable. 
    getClickableV2()
                            }                   
}
```

; 4. 

```
if (irisLevel < 2 * lMax + 10) ; Iris high enough to start with a ranger?
{
    switchToCombatTab()
    scrollDown(initDownClicks[1])
    toggleMode() ; toggle to progression mode
    lvlUp(firstStintTime, 0, 3, ++stint, stints, 1) ; nope, let's bridge with Samurai / phase 1
    scrollToBottom()
} else {
    scrollToBottom()
    toggleMode() ; toggle to progression mode
    if (firstStintTime > 0) {
        lvlUp(firstStintTime, 1, firstStintButton, ++stint, stints, 2) / phase 2
        scrollWayDown(3)
    }
}
if (midStintTime > 0) {
    lvlUp(midStintTime, 1, 2, ++stint, stints, 3) ; phase 3
    scrollWayDown(2)
}
checkClickable()
lvlUp(lastStintTime, 1, lastStintButton, ++stint, stints, 4) ; phase 4 / last phase



showSplash("Speed run completed.")
```

}

**Comment by swiftb** [comment]
The experimental branch (that got pushed out earlier today as a beta for v3.0 to the dev branch) solves the same problem with a normal image search that allow for some color variation. It has worked fine for both the "fish" and the Halloween candy, but if it breaks down in the future on some particularly tricky clickable, I might have to try something similar to this solution.

**Comment by swiftb** [comment]
Closing this issue since v3.x image recognition support works decently enough.
