### ISSUE TITLE
Ascend issue in steam mode

### ISSUE THREAD

**Issue by ErikTMA** [swiftb/clicker-heroes-sw1ft-bot#7]
I changed the yes button placement, in order to get it to work (default size)

; Ascend Yes button
xYes := 500
yYes := 500

was

; Ascend Yes button
xYes := 500
yYes := 445

**Comment by swiftb** [comment]
Fixed in the dev branch three days ago.

**Comment by swiftb** [comment]
Released in v3.0.2.
