### ISSUE TITLE
Update for Patch 0.25

### ISSUE THREAD

**Issue by dNhax** [swiftb/clicker-heroes-sw1ft-bot#9]
As v0.25 adds a new tab, the switchToRelicTab()-function needs a small fix by adding a negative x-offset (I tested with -40) to the clickPos().

```
switchToRelicTab() {
    global
    clickPos(xRelicTab-40, yTab)
    sleep % zzz * 2
}
```

Also, the getClickable()-function does not work correctly. It does not recognize the clickable (currently the orange fishy). May be a problem with the clickable_fish.png file (v0.25 seems to add an alpha value to the png).

Hopefully a fix will be committed soon. :-)

**Comment by Ellf** [comment]
Have you checked out the exp build?

https://github.com/swiftb/clicker-heroes-sw1ft-bot/tree/experimental

**Comment by swiftb** [comment]
It's the [dev branch](https://github.com/swiftb/clicker-heroes-sw1ft-bot/tree/dev) you want for 0.25.

Next push will fix the swap back to the clickable fish. Till then you can just remove the clickable.png and replace it with a renamed copy of the clickable_fish.png.

**Comment by Ellf** [comment]
Hah, yeah of course, that's the one I downloaded - just clicked back to the
wrong one - thanks for the correction :)

On 23 January 2016 at 19:34, swiftb notifications@github.com wrote:

> It's the dev branch
> https://github.com/swiftb/clicker-heroes-sw1ft-bot/tree/dev you want
> for 0.25.
> 
> Next push will fix the swap back to the clickable fish. Till then you can
> just remove the clickable.png and replace it with a renamed copy of the
> clickable_fish.png.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/swiftb/clicker-heroes-sw1ft-bot/issues/9#issuecomment-174215003
> .

## 

---

Show Me Teachable http://showme.ninja

**Comment by dNhax** [comment]
Hey guys,

I didn't check for other branches in this project, so.. my bad. ;-) Thanks a lot for your work and the quick replies!
